
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iiaedttaeytavfdejrgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpYWVkdHRhZXl0YXZmZGVqcmdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0ODMwODYsImV4cCI6MjA2MDA1OTA4Nn0.aCizmBR88bYvtKMPcZcceWthOXNiPuUk8ykF28SoyEI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
  }
});
